import React, { useState } from 'react';
import ReactMarkdown from 'react-markdown';
import {
  FileText,
  Copy,
  Check,
  Download,
  Sparkles,
  ChevronDown,
  ChevronRight,
} from 'lucide-react';
import Button from '../common/Button';

export default function FinalReportView({ report = '' }) {
  const [copied, setCopied] = useState(false);
  const [isExpanded, setIsExpanded] = useState(true);

  if (!report) return null;

  const handleCopy = () => {
    navigator.clipboard.writeText(report);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([report], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `code-review-report-${Date.now()}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="bg-[#11141a] border border-[#21262d] rounded-xl overflow-hidden shadow-sm">
      {/* Report Header Bar */}
      <div className="px-6 py-4 bg-[#161b22] border-b border-[#21262d] flex flex-col sm:flex-row sm:items-center justify-between gap-3">
        <div className="flex items-center gap-3">
          <div className="p-2 rounded-lg bg-indigo-500/10 text-indigo-400 border border-indigo-500/20">
            <FileText className="w-5 h-5" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h3 className="text-base font-bold text-zinc-100">
                Synthesized Code Review Report
              </h3>
              <span className="text-[10px] uppercase font-mono px-2 py-0.5 rounded bg-indigo-500/10 text-indigo-400 border border-indigo-500/20">
                Final Synthesis
              </span>
            </div>
            <p className="text-xs text-zinc-400 mt-0.5">
              Multi-agent synthesis generated by Groq LLM
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2 self-start sm:self-center">
          <Button
            type="button"
            variant="secondary"
            size="sm"
            onClick={handleDownload}
            icon={Download}
          >
            Download .md
          </Button>

          <Button
            type="button"
            variant={copied ? 'secondary' : 'primary'}
            size="sm"
            onClick={handleCopy}
            icon={copied ? Check : Copy}
          >
            {copied ? 'Copied' : 'Copy Report'}
          </Button>

          <button
            type="button"
            onClick={() => setIsExpanded(!isExpanded)}
            className="p-1.5 rounded text-zinc-400 hover:text-zinc-200 hover:bg-zinc-800 transition-colors"
          >
            {isExpanded ? <ChevronDown className="w-4 h-4" /> : <ChevronRight className="w-4 h-4" />}
          </button>
        </div>
      </div>

      {/* Markdown Content */}
      {isExpanded && (
        <div className="p-6 md:p-8 bg-[#0d1017]/50 text-zinc-300">
          <div className="markdown-report prose prose-invert max-w-none prose-headings:text-zinc-100 prose-headings:font-bold prose-h1:text-xl prose-h2:text-lg prose-h3:text-sm prose-p:text-xs prose-p:text-zinc-300 prose-p:leading-relaxed prose-li:text-xs prose-li:text-zinc-300 prose-code:font-mono prose-code:text-[11px] prose-code:bg-[#0a0c10] prose-code:px-1.5 prose-code:py-0.5 prose-code:rounded prose-code:border prose-code:border-[#21262d] prose-pre:bg-[#0a0c10] prose-pre:border prose-pre:border-[#21262d] prose-strong:text-zinc-100">
            <ReactMarkdown>{report}</ReactMarkdown>
          </div>
        </div>
      )}
    </div>
  );
}

